server:
  port: 10010
  servlet:
    session:
      timeout: -1
spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://192.168.10.232:3306/center_station?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: allong
#    url: jdbc:mysql:///center_station?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: allong
logging:
  level:
    com.allong.centerstation: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
